GET http://localhost/api/event
Accept: application/json

###

GET http://localhost/api/event/2
Accept: application/json

###

POST http://localhost/api/event
Accept: application/json
Content-Type: application/json

{
    "name": "123",
    "description": "Levar raio-x",
    "event_time": "02/08/2022 16:40",
    "email_to_notification": "test@cazco.digital"
}

###

PUT http://localhost/api/event/4
Accept: application/json
Content-Type: application/json

{
    "name": "Dentista",
    "description": "Levar raio-x",
    "event_time": "28/02/2020 17:30",
    "email_to_notification": "test@cazco.digital"
}

###

DELETE  http://localhost/api/event/5